### ISSUE TITLE
Have been unable to use account since creation. password resets don't work

### ISSUE THREAD

**Issue by Nathanpmyoung** [bellroy/predictionbook#202]
My account is nathanpmyoung, unable to log in. Password change doesn't help

**Comment by michaelwebb76** [comment]
Try `Nathanpmyoung`

**Comment by Nathanpmyoung** [comment]
I have tried that and creating a new account. Neither has worked. It doesn't even throw up errors, I just click the log in button beneath the password box, it refreshes and nothing happens.

**Comment by michaelwebb76** [comment]
@Nathanpmyoung I'm super confused by this. I've tested the signup process locally and can't find a problem with it, and I can't see anything obviously wrong with your signup data in the database apart from that leading capital letter in the login which doesn't match your original post. Obviously don't tell me your password, but are you using any strange characters in your password that might be different to most other users?

**Comment by Nathanpmyoung** [comment]
Should it say password incorrect? It doesn't do anything. Can you delete my
account so I can remake?

Yours,

Nathan Young

*M* 07891 020271
*W* nathanpmyoung.com
*T  ***@***.*** <https://twitter.com/nathanpmyoung>

UK Policy Forecast newsletter <https://tinyletter.com/decisionmaking>
Personal newsletter <https://tinyletter.com/nathan_young>

If I can put you in touch with someone, please ask.

Sent via Superhuman ***@***.***>

**Comment by michaelwebb76** [comment]
Deleted. Sorry for the delay, been off on hols.

**Comment by michaelwebb76** [comment]
Please close this issue if you're able to now recreate an account successfully.

**Comment by jaysonvirissimo** [comment]
The user [nathanpmyoung](https://predictionbook.com/users/nathanpmyoung) seems to have been active recently, so perhaps this issue can be closed now.

**Comment by Nathanpmyoung** [comment]
Yup I created my account again and it works

Yours,

Nathan Young

*M* 07891 020271
*W* nathanpmyoung.com
*T  ***@***.*** <https://twitter.com/nathanpmyoung>

UK Policy Forecast newsletter <https://tinyletter.com/decisionmaking>
Personal newsletter <https://tinyletter.com/nathan_young>

If I can put you in touch with someone, please ask.

Sent via Superhuman iOS ***@***.***>
