### ISSUE TITLE
Viewing specific pages of predictions crashses

### ISSUE THREAD

**Issue by Raemon** [bellroy/predictionbook#213]
When I navigate from my user profile to the second page of predictions (i.e. to: https://predictionbook.com/users/Raemon777/page/2 )

I get this crashed page:

<img width="1731" alt="image" src="https://user-images.githubusercontent.com/3246710/181415931-187b2ca1-fc34-42cb-8216-9ba0ca78c767.png">

**Comment by jaysonvirissimo** [comment]
Can confirm.
