### ISSUE TITLE
[BUG] Site is down

### ISSUE THREAD

**Issue by Sha-yol** [bellroy/predictionbook#243]
The website is down when browsing from chrome, for the past few days, displayes the following error:
![image](https://user-images.githubusercontent.com/32091466/226204113-a796f23c-17f8-4f05-bdaa-f68c2faa9bde.png)
There's no issue when browsing from Edge, or from incognito Chrome.
I suspected an extension interferes, but I disabled all extennsios and it didn't help.

**Comment by daniel-ziegler** [comment]
I'm also seeing this. I suspect something is causing an error for our user accounts.

**Comment by Sha-yol** [comment]
Ah, clearing cookies solved it for me, thanks!
