### ISSUE TITLE
Cannot judge predictions

### ISSUE THREAD

**Issue by sortega** [bellroy/predictionbook#244]
I cannot judge public nor private predictions. For example: https://predictionbook.com/predictions/197775

I get this screen:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/259587/229553951-b196aa09-4941-49d7-9edb-39276518eac8.png">

**Comment by sortega** [comment]
It's still happening.

**Comment by michaelwebb76** [comment]
Fixed. It was happening on all predictions in groups.
