### ISSUE TITLE
Feature request, data liberation and tags

### ISSUE THREAD

**Issue by andre-l-github** [bellroy/predictionbook#7]
Feature request:
- Add a field for free tags in predictions
- Allow me to download the predictions I've made

Rationale:
In general, I'd expect my forecasting biases to be topic dependent and horizon dependent. The horizon is already being recorded (when will you know), it'd be useful to tag predictions. 

For example, I may realize that I am being over confident about work related predictions and under confident about leisure related predictions. I also suspect I am less biased for predictions about the near future than predictions about the future.

Right now, the graph displaying the bias is pretty basic. I'd like to be able to download my prediction history as an XML or CSV file so I can look at the data through various angle. This data might also be used to train a machine learning algorithm that debiases predictions based on topic, horizon, etc. If I had enough predictions and cared enough, I could even set up a contest on Kaggle to see who can come up with the best model of my bias.

**Comment by btrettel** [comment]
Tagging predictions interests me as well. After a discussion with Will Kiely, I'm interested in users tagging themselves and/or joining a group as well, so you can see how well calibrated members of a group are or what their average probabilities are.

**Comment by jaysonvirissimo** [comment]
Related: https://github.com/bellroy/predictionbook/issues/130

**Comment by Sha-yol** [comment]
I second the request to allow downloading the data as CSV.

**Comment by michaelwebb76** [comment]
Tags and CSV export now available.
